### ISSUE TITLE
vite下面打包react后报错，请教怎么解决？

### ISSUE THREAD

**Issue by amydomi** [lgf196/JoL-player#13]
dev模式是正常的，build就报错无法运行。
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=object&args[]=

**Comment by lgf196** [comment]
可以给个案例吗？我好看下，放在codesandbox最好

**Comment by amydomi** [comment]
https://github.com/amydomi/vite-JoL-player.git

我把示例代码放我github仓库了，可以看下是什么原因，dev是正常的，build后浏览器里面出错，什么都不显示了。

**Comment by lgf196** [comment]
## 我这边打包:`npm run build`是可以的，如图
![image](https://user-images.githubusercontent.com/29600558/183011902-02db0f83-9b08-478d-ad3f-9f01d2d2c456.png)

#### 环境：`window10`
#### node: `v16`

### 你这边打包不成功，可以看下是否是`系统问题`，`node版本`问题，如果是`node版本问题`建议不要卸载`node`，直接安装一下`nvm`，然后切换不同的node版本来启动一下项目看看

**Comment by lgf196** [comment]
### `react`版本的`vite`脚手架我们这边写了一篇文章，很多的小伙伴react版本用vite，大多借鉴了我写的`vite-react-cil`
#### `vite-react-cil`博客文章地址：[vite-react-cil](https://juejin.cn/post/7016505733902499853)
#### 项目地址：[vite-react-cil](https://github.com/lgf196/vite-react-cil/blob/master/zh.md)

**Comment by amydomi** [comment]
我用的就是nvm安装的node，版本：16.15.1

使用npm run build 编译后再运行编译后的文件，浏览器报错。

`index.8c8311d5.js:32 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Bi (index.8c8311d5.js:32:49749)
    at x (index.8c8311d5.js:30:17372)
    at ht (index.8c8311d5.js:32:1494)
    at td (index.8c8311d5.js:32:46106)
    at Qc (index.8c8311d5.js:32:40042)
    at vh (index.8c8311d5.js:32:39970)
    at so (index.8c8311d5.js:32:39824)
    at Ha (index.8c8311d5.js:32:36159)
    at qc (index.8c8311d5.js:32:35107)
    at c (index.8c8311d5.js:17:1535)
Ra @ index.8c8311d5.js:32
index.8c8311d5.js:32 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Bi (index.8c8311d5.js:32:49749)
    at x (index.8c8311d5.js:30:17372)
    at ht (index.8c8311d5.js:32:1494)
    at td (index.8c8311d5.js:32:46106)
    at Qc (index.8c8311d5.js:32:40042)
    at vh (index.8c8311d5.js:32:39970)
    at so (index.8c8311d5.js:32:39824)
    at Ha (index.8c8311d5.js:32:36159)
    at qc (index.8c8311d5.js:32:35107)
    at c (index.8c8311d5.js:17:1535)`

**Comment by lgf196** [comment]
## ` Minified React error #130`的问题已修复

安装新的版本，`npm install jol-player@3.5.0 --save`

## 注意：引入方式发生变化了
```
import { JolPlayer } from "jol-player";
```
这样引入才能在打包正式环境下运行，解决`vite`环境下的bug

**Comment by amydomi** [comment]
我用新版本，问题还没解决，还在报这个相同的错误。
